version: '3.7'

services:

  api:
    build: .
    depends_on:
      - postgres15
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  postgres15:
    container_name: postgres15
    hostname: localhost
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=webtronics_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
    driver: "local"